name: Continuous Integration

on:
 push:
  branches:
    -main

jobs:

test:

 runs-on: ubuntu-latest

 steps:

  -name: Checkout Repository
  uses: actions/checkout@v4

  -name: Verify HTML File Exists
  run: test -f index.HTML

  -name: Verify CSS File Exists
  run: test -f style.CSS

  -name: Verify javaScript File Exists
  run: test -f script.js
  
  -name: CI Successful
  run: echo "Website passed Validation"

